# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'yeni_gui3.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1204, 909)
        MainWindow.setStyleSheet("background-color: rgb(235, 235, 235);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.camera_label = QtWidgets.QLabel(self.centralwidget)
        self.camera_label.setGeometry(QtCore.QRect(40, 170, 640, 640))
        self.camera_label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.camera_label.setText("")
        self.camera_label.setObjectName("camera_label")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(50, 30, 649, 121))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.fps_label = QtWidgets.QLabel(self.layoutWidget)
        self.fps_label.setStyleSheet("QLabel#fps_label {\n"
"    padding: 10px;\n"
"    border-radius: 15px;\n"
"    background: qlineargradient(\n"
"        spread: pad, x1:0, y1:0, x2:1, y2:1, \n"
"        stop: 0 #b0b0b0, stop: 1 #e0e0e0);\n"
"    color: black;\n"
"    font: bold 14px \'Arial\';\n"
"    text-align: center;\n"
"}\n"
"")
        self.fps_label.setScaledContents(True)
        self.fps_label.setAlignment(QtCore.Qt.AlignCenter)
        self.fps_label.setWordWrap(False)
        self.fps_label.setIndent(-1)
        self.fps_label.setOpenExternalLinks(True)
        self.fps_label.setObjectName("fps_label")
        self.horizontalLayout.addWidget(self.fps_label)
        self.model_label = QtWidgets.QLabel(self.layoutWidget)
        self.model_label.setStyleSheet("QLabel#model_label {\n"
"    padding: 10px;\n"
"    border-radius: 15px;\n"
"    background: qlineargradient(\n"
"        spread: pad, x1:0, y1:0, x2:1, y2:1, \n"
"        stop: 0 #b0b0b0, stop: 1 #e0e0e0);\n"
"    color: black;\n"
"    font: bold 14px \'Arial\';\n"
"    text-align: center;\n"
"}\n"
"")
        self.model_label.setScaledContents(True)
        self.model_label.setAlignment(QtCore.Qt.AlignCenter)
        self.model_label.setWordWrap(False)
        self.model_label.setIndent(-1)
        self.model_label.setOpenExternalLinks(True)
        self.model_label.setObjectName("model_label")
        self.horizontalLayout.addWidget(self.model_label)
        self.person_label = QtWidgets.QLabel(self.layoutWidget)
        self.person_label.setStyleSheet("QLabel#person_label {\n"
"    padding: 10px;\n"
"    border-radius: 15px;\n"
"    background: qlineargradient(\n"
"        spread: pad, x1:0, y1:0, x2:1, y2:1, \n"
"        stop: 0 #b0b0b0, stop: 1 #e0e0e0);\n"
"    color: black;\n"
"    font: bold 14px \'Arial\';\n"
"    text-align: center;\n"
"}\n"
"")
        self.person_label.setScaledContents(True)
        self.person_label.setAlignment(QtCore.Qt.AlignCenter)
        self.person_label.setWordWrap(False)
        self.person_label.setIndent(-1)
        self.person_label.setOpenExternalLinks(True)
        self.person_label.setObjectName("person_label")
        self.horizontalLayout.addWidget(self.person_label)
        self.provider_label = QtWidgets.QLabel(self.layoutWidget)
        self.provider_label.setStyleSheet("QLabel#provider_label {\n"
"    padding: 10px;\n"
"    border-radius: 15px;\n"
"    background: qlineargradient(\n"
"        spread: pad, x1:0, y1:0, x2:1, y2:1, \n"
"        stop: 0 #b0b0b0, stop: 1 #e0e0e0);\n"
"    color: black;\n"
"    font: bold 14px \'Arial\';\n"
"    text-align: center;\n"
"}\n"
"")
        self.provider_label.setScaledContents(True)
        self.provider_label.setAlignment(QtCore.Qt.AlignCenter)
        self.provider_label.setWordWrap(False)
        self.provider_label.setIndent(-1)
        self.provider_label.setOpenExternalLinks(True)
        self.provider_label.setObjectName("provider_label")
        self.horizontalLayout.addWidget(self.provider_label)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(690, 180, 361, 101))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.iou_label = QtWidgets.QLabel(self.layoutWidget1)
        self.iou_label.setStyleSheet("QLabel#iou_label {\n"
"    padding: 10px;\n"
"    border-radius: 15px;\n"
"    background: qlineargradient(\n"
"        spread: pad, x1:0, y1:0, x2:1, y2:1, \n"
"        stop: 0 #b0b0b0, stop: 1 #e0e0e0);\n"
"    color: black;\n"
"    font: bold 14px \'Arial\';\n"
"    text-align: center;\n"
"}\n"
"")
        self.iou_label.setAlignment(QtCore.Qt.AlignCenter)
        self.iou_label.setObjectName("iou_label")
        self.gridLayout.addWidget(self.iou_label, 0, 0, 1, 1)
        self.iou_slider = QtWidgets.QSlider(self.layoutWidget1)
        self.iou_slider.setOrientation(QtCore.Qt.Horizontal)
        self.iou_slider.setObjectName("iou_slider")
        self.gridLayout.addWidget(self.iou_slider, 0, 1, 1, 1)
        self.iou_label_value = QtWidgets.QLabel(self.layoutWidget1)
        self.iou_label_value.setStyleSheet("QLabel#iou_label_value {\n"
"    padding: 10px;\n"
"    border-radius: 15px;\n"
"    background: qlineargradient(\n"
"        spread: pad, x1:0, y1:0, x2:1, y2:1, \n"
"        stop: 0 #b0b0b0, stop: 1 #e0e0e0);\n"
"    color: black;\n"
"    font: bold 14px \'Arial\';\n"
"    text-align: center;\n"
"}\n"
"")
        self.iou_label_value.setText("")
        self.iou_label_value.setObjectName("iou_label_value")
        self.gridLayout.addWidget(self.iou_label_value, 0, 2, 1, 1)
        self.conf_label = QtWidgets.QLabel(self.layoutWidget1)
        self.conf_label.setStyleSheet("QLabel#conf_label {\n"
"    padding: 10px;\n"
"    border-radius: 15px;\n"
"    background: qlineargradient(\n"
"        spread: pad, x1:0, y1:0, x2:1, y2:1, \n"
"        stop: 0 #b0b0b0, stop: 1 #e0e0e0);\n"
"    color: black;\n"
"    font: bold 14px \'Arial\';\n"
"    text-align: center;\n"
"}\n"
"")
        self.conf_label.setObjectName("conf_label")
        self.gridLayout.addWidget(self.conf_label, 1, 0, 1, 1)
        self.conf_slider = QtWidgets.QSlider(self.layoutWidget1)
        self.conf_slider.setOrientation(QtCore.Qt.Horizontal)
        self.conf_slider.setObjectName("conf_slider")
        self.gridLayout.addWidget(self.conf_slider, 1, 1, 1, 1)
        self.conf_label_value = QtWidgets.QLabel(self.layoutWidget1)
        self.conf_label_value.setStyleSheet("QLabel#conf_label_value {\n"
"    padding: 10px;\n"
"    border-radius: 15px;\n"
"    background: qlineargradient(\n"
"        spread: pad, x1:0, y1:0, x2:1, y2:1, \n"
"        stop: 0 #b0b0b0, stop: 1 #e0e0e0);\n"
"    color: black;\n"
"    font: bold 14px \'Arial\';\n"
"    text-align: center;\n"
"}\n"
"")
        self.conf_label_value.setText("")
        self.conf_label_value.setObjectName("conf_label_value")
        self.gridLayout.addWidget(self.conf_label_value, 1, 2, 1, 1)
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(690, 310, 361, 38))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.choose_model = QtWidgets.QLabel(self.layoutWidget2)
        self.choose_model.setStyleSheet("QLabel#choose_model {\n"
"    padding: 10px;\n"
"    border-radius: 15px;\n"
"    background: qlineargradient(\n"
"        spread: pad, x1:0, y1:0, x2:1, y2:1, \n"
"        stop: 0 #b0b0b0, stop: 1 #e0e0e0);\n"
"    color: black;\n"
"    font: bold 14px \'Arial\';\n"
"    text-align: center;\n"
"}\n"
"")
        self.choose_model.setAlignment(QtCore.Qt.AlignCenter)
        self.choose_model.setObjectName("choose_model")
        self.gridLayout_2.addWidget(self.choose_model, 0, 0, 1, 1)
        self.model_box = QtWidgets.QComboBox(self.layoutWidget2)
        self.model_box.setStyleSheet("QComboBox#model_box {\n"
"    padding: 5px;\n"
"    border: 1px solid #b0b0b0;\n"
"    border-radius: 5px;\n"
"    background-color: #f0f0f0;\n"
"    color: black;\n"
"    font: 14px \'Arial\';\n"
"}\n"
"\n"
"QComboBox#model_box::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 15px;\n"
"    border-left: 1px solid #b0b0b0;\n"
"}\n"
"\n"
"QComboBox#model_box::down-arrow {\n"
"    image: url(down_arrow.png); /* İstediğiniz ok işareti resmi */\n"
"    width: 10px;\n"
"    height: 10px;\n"
"}\n"
"\n"
"QComboBox#model_box QAbstractItemView {\n"
"    border: 1px solid #b0b0b0;\n"
"    background-color: #ffffff;\n"
"    selection-background-color: #d0d0d0;\n"
"    selection-color: black;\n"
"    padding: 5px;\n"
"}\n"
"")
        self.model_box.setObjectName("model_box")
        self.gridLayout_2.addWidget(self.model_box, 0, 1, 1, 1)
        self.layoutWidget3 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget3.setGeometry(QtCore.QRect(691, 500, 361, 81))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.open_camera = QtWidgets.QPushButton(self.layoutWidget3)
        self.open_camera.setStyleSheet("QPushButton#open_camera {\n"
"    padding: 10px;\n"
"    border-radius: 15px;\n"
"    background: qlineargradient(\n"
"        spread: pad, x1:0, y1:0, x2:1, y2:1, \n"
"        stop: 0 #b0b0b0, stop: 1 #e0e0e0);\n"
"    color: black;\n"
"    font: bold 14px \'Arial\';\n"
"    text-align: center;\n"
"}\n"
"\n"
"QPushButton#open_camera:hover {\n"
"    background: qlineargradient(\n"
"        spread: pad, x1:0, y1:0, x2:1, y2:1, \n"
"        stop: 0 #e0e0e0, stop: 1 #b0b0b0);\n"
"}\n"
"")
        self.open_camera.setObjectName("open_camera")
        self.horizontalLayout_2.addWidget(self.open_camera)
        self.stop_camera = QtWidgets.QPushButton(self.layoutWidget3)
        self.stop_camera.setStyleSheet("QPushButton#stop_camera {\n"
"    padding: 10px;\n"
"    border-radius: 15px;\n"
"    background: qlineargradient(\n"
"        spread: pad, x1:0, y1:0, x2:1, y2:1, \n"
"        stop: 0 #b0b0b0, stop: 1 #e0e0e0);\n"
"    color: black;\n"
"    font: bold 14px \'Arial\';\n"
"    text-align: center;\n"
"}\n"
"\n"
"QPushButton#stop_camera:hover {\n"
"    background: qlineargradient(\n"
"        spread: pad, x1:0, y1:0, x2:1, y2:1, \n"
"        stop: 0 #e0e0e0, stop: 1 #b0b0b0);\n"
"}\n"
"")
        self.stop_camera.setObjectName("stop_camera")
        self.horizontalLayout_2.addWidget(self.stop_camera)
        self.layoutWidget4 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget4.setGeometry(QtCore.QRect(690, 370, 361, 38))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.kamera_sec = QtWidgets.QLabel(self.layoutWidget4)
        self.kamera_sec.setStyleSheet("QLabel#kamera_sec {\n"
"    padding: 10px;\n"
"    border-radius: 15px;\n"
"    background: qlineargradient(\n"
"        spread: pad, x1:0, y1:0, x2:1, y2:1, \n"
"        stop: 0 #b0b0b0, stop: 1 #e0e0e0);\n"
"    color: black;\n"
"    font: bold 14px \'Arial\';\n"
"    text-align: center;\n"
"}\n"
"")
        self.kamera_sec.setAlignment(QtCore.Qt.AlignCenter)
        self.kamera_sec.setObjectName("kamera_sec")
        self.horizontalLayout_3.addWidget(self.kamera_sec)
        self.camera_box = QtWidgets.QComboBox(self.layoutWidget4)
        self.camera_box.setStyleSheet("QComboBox#camera_box {\n"
"    padding: 5px;\n"
"    border: 1px solid #b0b0b0;\n"
"    border-radius: 5px;\n"
"    background-color: #f0f0f0;\n"
"    color: black;\n"
"    font: 14px \'Arial\';\n"
"}\n"
"\n"
"QComboBox#camera_box::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 15px;\n"
"    border-left: 1px solid #b0b0b0;\n"
"}\n"
"\n"
"QComboBox#camera_box::down-arrow {\n"
"    image: url(down_arrow.png); /* İstediğiniz ok işareti resmi */\n"
"    width: 10px;\n"
"    height: 10px;\n"
"}\n"
"\n"
"QComboBox#camera_box QAbstractItemView {\n"
"    border: 1px solid #b0b0b0;\n"
"    background-color: #ffffff;\n"
"    selection-background-color: #d0d0d0;\n"
"    selection-color: black;\n"
"    padding: 5px;\n"
"}\n"
"")
        self.camera_box.setObjectName("camera_box")
        self.horizontalLayout_3.addWidget(self.camera_box)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(691, 431, 361, 38))
        self.widget.setObjectName("widget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.kamera_sec_2 = QtWidgets.QLabel(self.widget)
        self.kamera_sec_2.setStyleSheet("QLabel#kamera_sec_2 {\n"
"    padding: 10px;\n"
"    border-radius: 15px;\n"
"    background: qlineargradient(\n"
"        spread: pad, x1:0, y1:0, x2:1, y2:1, \n"
"        stop: 0 #b0b0b0, stop: 1 #e0e0e0);\n"
"    color: black;\n"
"    font: bold 14px \'Arial\';\n"
"    text-align: center;\n"
"}\n"
"")
        self.kamera_sec_2.setAlignment(QtCore.Qt.AlignCenter)
        self.kamera_sec_2.setObjectName("kamera_sec_2")
        self.horizontalLayout_4.addWidget(self.kamera_sec_2)
        self.kamer_sec_line = QtWidgets.QLineEdit(self.widget)
        self.kamer_sec_line.setStyleSheet("QLineEdit#kamera_sec_line {\n"
"    padding: 5px;\n"
"    border: 1px solid #b0b0b0;\n"
"    border-radius: 5px;\n"
"    background-color: #f0f0f0;\n"
"    color: black;\n"
"    font: 14px \'Arial\';\n"
"}\n"
"\n"
"QLineEdit#kamera_sec_line::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 15px;\n"
"    border-left: 1px solid #b0b0b0;\n"
"}\n"
"\n"
"QLineEdit#kamera_sec_line::down-arrow {\n"
"    image: url(down_arrow.png); /* İstediğiniz ok işareti resmi */\n"
"    width: 10px;\n"
"    height: 10px;\n"
"}\n"
"\n"
"QLineEdit#kamera_sec_line QAbstractItemView {\n"
"    border: 1px solid #b0b0b0;\n"
"    background-color: #ffffff;\n"
"    selection-background-color: #d0d0d0;\n"
"    selection-color: black;\n"
"    padding: 5px;\n"
"}\n"
"")
        self.kamer_sec_line.setObjectName("kamer_sec_line")
        self.horizontalLayout_4.addWidget(self.kamer_sec_line)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "HSE Person Detection "))
        self.fps_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Fps</span></p><hr/><p align=\"center\"><span style=\" font-size:12pt;\">{fps_value}</span></p></body></html>"))
        self.model_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Use Model</span></p><hr/><p align=\"center\"><span style=\" font-size:12pt;\">{model_text}</span></p></body></html>"))
        self.person_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Detection Person</span></p><hr/><p align=\"center\"><span style=\" font-size:12pt;\">{person_value}</span></p></body></html>"))
        self.provider_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">PROVİDER</span></p><hr/><p align=\"center\"><span style=\" font-size:12pt;\">{provider_value}</span></p></body></html>"))
        self.iou_label.setText(_translate("MainWindow", "İoU Value"))
        self.conf_label.setText(_translate("MainWindow", "Conf Threshold"))
        self.choose_model.setText(_translate("MainWindow", "Choose Model"))
        self.open_camera.setText(_translate("MainWindow", "Open Camera"))
        self.stop_camera.setText(_translate("MainWindow", "Stop Camera"))
        self.kamera_sec.setText(_translate("MainWindow", "Choose camera"))
        self.kamera_sec_2.setText(_translate("MainWindow", "Enter Camera Ip"))
